Repository fungover/system2024, pull requests merged in 2024-12, with the labels that each got.

#33 #16 - Create react
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  readme.md
Labels: enhancement

#83 Fix Vite Output Directory to Root Project Static Folder
  frontend/vite.config.ts
  src/main/resources/static/assets/index-BanxF_bj.js
  src/main/resources/static/assets/index-n_ryQ3BS.css
  src/main/resources/static/assets/react-CHdo91hT.svg
  src/main/resources/static/index.html
  src/main/resources/static/vite.svg
Labels: bug, High Priority

#74 73 create tests for graphql queries and custom exceptions
  src/main/java/org/fungover/system2024/exception/GraphQLExceptionResolver.java
  src/test/java/org/fungover/system2024/controller/UserControllerIntTest.java
Labels: Integration test

#76 API Documentation with Swagger
  pom.xml
  readme.md
  src/main/java/org/fungover/system2024/config/OpenApiConfig.java
Labels: documentation, enhancement

#67 #25 Unit tests for User, Role and Permission Entities
  .github/workflows/ci.yml
  logs/app.log
  pom.xml
  readme.md
  src/main/java/org/fungover/system2024/controller/LoginController.java
  src/main/java/org/fungover/system2024/file/FileDTO.java
  src/main/java/org/fungover/system2024/file/FileService.java
  src/main/java/org/fungover/system2024/file/entity/File.java
  src/main/java/org/fungover/system2024/user/entity/BaseEntity.java
  src/main/java/org/fungover/system2024/user/entity/User.java
  src/main/resources/application.properties
  src/main/resources/file_schema.sql
  src/main/resources/file_test_schema.sql
  src/main/resources/schema.sql
  src/test/java/org/fungover/system2024/entities/PermissionTest.java
  src/test/java/org/fungover/system2024/entities/RoleTest.java
  src/test/java/org/fungover/system2024/entities/UserTest.java
Labels: unit tests
